### ISSUE TITLE
Idee: Python-Syntax hacken, um direkt MQTT-Ausdrücke zu erlauben

### ISSUE THREAD

**Issue by scy** [ewaldshof/ewhome#11]
Ein Bekannter von mir hat mir einen Tipp gegeben, wie sich Python manipulieren lässt, um bereits mit Funktionalität belegte Zeichen (z.B. `/`) anders zu interpretieren: https://gist.github.com/L3viathan/92addec9501969ae628c90b9100f3177

Das Beispiel parst Mailadressen, die direkt im Code stehen (also nicht als String). Ich hab noch nicht ganz verstanden, wie es funktioniert, und ich glaube auch nicht, dass wir das wirklich brauchen, aber ich wollte es zumindest mal irgendwo niedergeschrieben haben. Damit könnten wir quasi das Regex-basierte Ersetzen von MQTT-Pfaden in der Config durch diese Variante hier ersetzen.

**Comment by sulimma** [comment]
Hier ist noch ein anderer Ansatz:
https://medium.com/better-programming/adding-sugar-to-the-python-syntax-e89248ce6e72

**Comment by sulimma** [comment]
Ich halte es aber auch für unnötig.
