### ISSUE TITLE
Kritischer BUG: Pinzuordnung geht verloren

### ISSUE THREAD

**Issue by sulimma** [ewaldshof/ewhome#20]
Wir dachten, Boards würden kaputt gehen.

Tatsächlich sieht es jetzt aber so aus, als würde die Zuordnung von Klemmen zu Pins verloren gehen. 
Jedenfalls ist es bei Boards die zunächst einwandfrei funktioniert haben, nicht mehr möglich, Werte an Ausgangspins zuzuweisen, zumindest bei den meisten Pins.
Komisch ist, dass das mit einem Reboot des Boards nicht weg geht.
Wenn ich ins REPL gehe und den Pin von Hand setze funktioniert er jedoch.

**Comment by scy** [comment]
Ich hab gerade mal kurz durch den Code geschaut und auf den ersten Blick nichts auffälliges gefunden. Müsste man mal intensiver debuggen. Sind vielleicht irgendwelche Expressions fehlerhaft? Tritt irgendwo ne Exception auf? Schlägt die MQTT-Subscription fehl?

**Comment by sulimma** [comment]
Sollte noch besser getestet werden, aber es sieht so aus, als hätte   @scy das heute behoben.
