### ISSUE TITLE
sync-code fails if there are existing files on the board

### ISSUE THREAD

**Issue by sulimma** [ewaldshof/ewhome#21]
I tried to sync a precompiled firmware over an existing firmware with .py files. The script failed.
This was done under Debian Linux in Windows 10 WSL 2 with python 3.8.
Deleting all files on the board manually with ampy did solve the issue.

The script should either be able to delete these files by itself or faile gracefully with an error message that informs the user about what s/he can do to proceed.

The script fails with one of the following two errors:

a)
sending incremental file list
deleting temperature.mpy
deleting task.mpy
deleting name.mpy
deleting mqtt.mpy
deleting heartbeat.mpy
deleting ewh_net.mpy
deleting display.mpy
deleting config.mpy
deleting board/bohei.mpy
deleting board/base.mpy
deleting board/__init__.mpy
deleting drivers/ssd1306.mpy
deleting drivers/__init__.mpy
deleting parts/slow_pwm.mpy
deleting parts/proportional.mpy
deleting parts/output_pins.mpy
deleting parts/input_pins.mpy
deleting parts/config_dumper.mpy
deleting parts/assign.mpy
deleting parts/__init__.mpy
./
config.py
display.py
ewh_net.py
heartbeat.py
mqtt.py
name.py
task.py
temperature.py
board/
board/__init__.py
board/base.py
board/bohei.py
drivers/
drivers/__init__.py
drivers/ssd1306.py
parts/
parts/__init__.py
parts/assign.py
parts/config_dumper.py
parts/input_pins.py
parts/output_pins.py
parts/proportional.py
parts/slow_pwm.py

sent 37,690 bytes  received 803 bytes  25,662.00 bytes/sec
total size is 36,873  speedup is 0.96
Precompiling ...
... done.
Using buffer-size of 32
Connecting to /dev/ttyS3 (buffer-size 32)...
Trying to connect to REPL  connected
Testing if ubinascii.unhexlify exists ... Y
Retrieving root directories ... /drivers/ /board/ /heating.py/ /task.py/ /config.py/ /boot.py/ /ewh_net.py/ /mqtt.py/ /temperature.py/ /display.py/ /heartbeat.py/ /name.py/ /parts/
Setting time ... Dec 23, 2020 21:29:34
Evaluating board_name ... pyboard
Retrieving time epoch ... Jan 01, 2000
Adding /pyboard/temperature.mpy
timed out or error in transfer to remote: b'\x04'

===================================
b)
sending incremental file list
deleting temperature.mpy
deleting task.mpy
deleting name.mpy
deleting mqtt.mpy
deleting heartbeat.mpy
deleting ewh_net.mpy
deleting display.mpy
deleting config.mpy
deleting board/bohei.mpy
deleting board/base.mpy
deleting board/__init__.mpy
deleting drivers/ssd1306.mpy
deleting drivers/__init__.mpy
deleting parts/slow_pwm.mpy
deleting parts/proportional.mpy
deleting parts/output_pins.mpy
deleting parts/input_pins.mpy
deleting parts/config_dumper.mpy
deleting parts/assign.mpy
deleting parts/__init__.mpy
./
config.py
display.py
ewh_net.py
heartbeat.py
mqtt.py
name.py
task.py
temperature.py
board/
board/__init__.py
board/base.py
board/bohei.py
drivers/
drivers/__init__.py
drivers/ssd1306.py
parts/
parts/__init__.py
parts/assign.py
parts/config_dumper.py
parts/input_pins.py
parts/output_pins.py
parts/proportional.py
parts/slow_pwm.py

sent 37,690 bytes  received 803 bytes  76,986.00 bytes/sec
total size is 36,873  speedup is 0.96
Precompiling ...
... done.
Using buffer-size of 32
Connecting to /dev/ttyS3 (buffer-size 32)...
Trying to connect to REPL  connected
Testing if ubinascii.unhexlify exists ... Y
Retrieving root directories ... /drivers/ /board/ /heating.py/ /task.py/ /config.py/ /boot.py/ /ewh_net.py/ /mqtt.py/ /temperature.py/ /display.py/ /heartbeat.py/ /name.py/ /parts/
Setting time ... Traceback (most recent call last):
  File "/home/kolja/.local/share/virtualenvs/ewhome-JqXEgid_/lib/python3.8/site-packages/rshell/main.py", line 1307, in connect
    ip_address = socket.gethostbyname(port)
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kolja/.local/share/virtualenvs/ewhome-JqXEgid_/bin/rshell", line 8, in <module>
    sys.exit(main())
  File "/home/kolja/.local/share/virtualenvs/ewhome-JqXEgid_/lib/python3.8/site-packages/rshell/command_line.py", line 4, in main
    rshell.main.main()
  File "/home/kolja/.local/share/virtualenvs/ewhome-JqXEgid_/lib/python3.8/site-packages/rshell/main.py", line 2966, in main
    real_main()
  File "/home/kolja/.local/share/virtualenvs/ewhome-JqXEgid_/lib/python3.8/site-packages/rshell/main.py", line 2928, in real_main
    connect(args.port, baud=args.baud, wait=args.wait, user=args.user, password=args.password)
  File "/home/kolja/.local/share/virtualenvs/ewhome-JqXEgid_/lib/python3.8/site-packages/rshell/main.py", line 1313, in connect
    connect_serial(port, baud=baud, wait=wait)
  File "/home/kolja/.local/share/virtualenvs/ewhome-JqXEgid_/lib/python3.8/site-packages/rshell/main.py", line 1337, in connect_serial
    dev = DeviceSerial(port, baud, wait)
  File "/home/kolja/.local/share/virtualenvs/ewhome-JqXEgid_/lib/python3.8/site-packages/rshell/main.py", line 1627, in __init__
    Device.__init__(self, pyb)
  File "/home/kolja/.local/share/virtualenvs/ewhome-JqXEgid_/lib/python3.8/site-packages/rshell/main.py", line 1399, in __init__
    now = self.sync_time()
  File "/home/kolja/.local/share/virtualenvs/ewhome-JqXEgid_/lib/python3.8/site-packages/rshell/main.py", line 1537, in sync_time
    self.remote(set_time, (now.tm_year, now.tm_mon, now.tm_mday, now.tm_wday + 1,
  File "/home/kolja/.local/share/virtualenvs/ewhome-JqXEgid_/lib/python3.8/site-packages/rshell/main.py", line 1495, in remote
    output = self.pyb.exec_raw_no_follow(func_src)
  File "/home/kolja/.local/share/virtualenvs/ewhome-JqXEgid_/lib/python3.8/site-packages/rshell/pyboard.py", line 250, in exec_raw_no_follow
    raise PyboardError('could not exec command')
rshell.pyboard.PyboardError: could not exec command

**Comment by scy** [comment]
Both of these errors are thrown by rshell, not the build script.

To me, they look like the usual woes that go along with trying to work with ESP boards under WSL, or maybe even Windows in general.

My solution was to develop on a Raspberry Pi, i.e. a real Linux system, instead. I know, that’s probably not what you’d like to hear, but all of the USB serial instability completely went away.

However, I see that you had a `boot.py` on your board. Depending on what’s in that file, it can seriously interfere with rshell and/or ampy. Nowadays I try to keep `boot.py` completely empty and put all of my startup code in `main.py`. That helped a lot, too.
